# Site settings
title: Sami Osborn
description: >-
  Machine learning and robotics articles and builds. 
baseurl: ""
url: ""
github_username: samiosborn

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:category/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Exclude from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
