title: Sami Osborn
description: Mathematical systems builder working across robotics, perception, control, and learning.
baseurl: ""
url: ""
github_username: samiosborn
timezone: Europe/London
theme: minima
permalink: pretty

plugins:
  - jekyll-feed
